version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notify.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - 5672:5672
      - 1084:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
