export enum APIExample {
  IsDraft = 'true',
  IsRepost = 'false',
  Type = 'video',
  Id = '638a5bbf4ca776bd324605df',
  Tag = 'tag',
  WebLink = 'https =//link.subdomain.domain',
  Desc = 'Post description example',
  Title = 'Post title example',
  Ann = 'Lorem ipsum dolor sit amet.',
  Text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In malesuada.',
  Quote = 'Lorem ipsum dolor sit amet.',
  Author = 'John Doe',
  PhotoLink = '/upload/photo.jpg',
  VideoLink = 'https =//youtube.com/video',
  Limit = '12',
  Posts = '33',
  Subscribers = '123',
  CommentId = '123',
  PostId  = '2',
  Comment = 'Lorem ipsum dolor set amet',
  Avatar = 'file',
  Photo = 'file',
  FilePath = '/dir/file.png',
  Email = 'address@domain.domain',
  UserId = '63ce83ff67458e1098ea7ae2',
  Name = 'John Doe',
  Password = 'p4ssw0rd',
  Token = 'ajefio2fu4o2yf084ursdfjeinqc;urn3rc',
}
