# Create a new link post
POST http://localhost:3333/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTU2OTc3LCJleHAiOjE2NzM5NjI5Nzd9.8P72ylxSHcrgIM91DEZ-82uuJAlNMeocBA2exkRf4d4
Content-Type: application/json

{
  "type": "link",
  "content": {
    "url": "http://test.link.com",
    "desc": "test link description"
  },
  "tags": [ "tag", "tag", "anotherTag" ]
}

###

# Delete the post by its id
DELETE http://localhost:3333/api/posts/delete/13 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzllNzM5ODFjYTkwM2ExMGVhNjNmYTMiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLm9iZWJhcyIsImlhdCI6MTY3Mzk0NzA2OCwiZXhwIjoxNjczOTUzMDY4fQ.e8DOgRZ5hn3tTyyu5QWd1ryhrQGMrkyXHpJTQsjI7hM

###

# Get post by postid
GET http://localhost:3333/api/posts/post/9 HTTP/1.1

###

# Get posts feed
GET http://localhost:3333/api/posts/feed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTU0MjI0LCJleHAiOjE2NzM5NjAyMjR9.nGJgl6CXK1Ouub-4Vex_hzbqfn4E65kLypPqW2WYvqY

###

# Get posts by tag
GET http://localhost:3333/api/posts/tag/anothertag
###

###

# Get posts by type
GET http://localhost:3333/api/posts/type/link
###


# Sort posts by likes
GET http://localhost:3333/api/posts?sortBy=likes
###

# Sort posts by comments
GET http://localhost:3333/api/posts?sortBy=comments
###

# Repost post by id
POST http://localhost:3333/api/posts/repost/9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTUwOTA5LCJleHAiOjE2NzM5NTY5MDl9.7ro3iSsrZG0WWoDjzyNeKoxpuc9RWHHsZQh2wbZ_vo4


###

# Like post by id
POST http://localhost:3333/api/posts/like/6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTUwOTA5LCJleHAiOjE2NzM5NTY5MDl9.7ro3iSsrZG0WWoDjzyNeKoxpuc9RWHHsZQh2wbZ_vo4

###

# Get all posts
GET http://localhost:3333/api/posts HTTP/1.1

###

#Update post by id
PATCH  http://localhost:3333/api/posts/update/57 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTUwOTA5LCJleHAiOjE2NzM5NTY5MDl9.7ro3iSsrZG0WWoDjzyNeKoxpuc9RWHHsZQh2wbZ_vo4
Content-Type: application/json

{
  "type": "quote",
  "quote": {
    "author": "John Doe",
    "quote": "Lorem ipsum dolor set amet"
  },
  "isDraft": true,
  "tags": ["tag"]
}

###

# Send unread posts to email
POST http://localhost:3333/api/posts/notify/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTU2OTc3LCJleHAiOjE2NzM5NjI5Nzd9.8P72ylxSHcrgIM91DEZ-82uuJAlNMeocBA2exkRf4d4

###
