import { ContentType } from "@prisma/client"

export const APIExample = {
  IsDraft: true,
  IsRepost: false,
  Type: ContentType.VIDEO,
  PostID: 22,
  Tag: 'tag',
  WebLink: 'https://link.subdomain.domain',
  Desc: 'Post description example',
  Title: 'Post title example',
  Ann: 'Lorem ipsum dolor sit amet.',
  Text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In malesuada.',
  Quote: 'Lorem ipsum dolor sit amet.',
  Author: 'John Doe',
  PhotoLink: '/upload/photo.jpg',
  VideoLink: 'https://youtube.com/video',
  Limit: 12,
  Posts: 33,
  Subscribers: 123,
  CommentID: 123,
  Comment: 'Lorem ipsum dolor set amet',
  Avatar: 'file',
  Photo: 'file',
  FilePath: '/dir/file.png',
  Email: 'address@domain.domain',
  UserID: 'fewvqr2f12fe1wd',
  Name: 'User',
  Password: 'p4ssw0rd',
  Token: 'ajefio2fu4o2yf084ursdfjeinqc;urn3rc',
}
