# Create new comment for post by id
POST http://localhost:5555/api/mail/ HTTP/1.1
Content-Type: application/json

{
  "email": "user@email.com",
  "name": "User User",
  "postIDs": [
    "33", "38", "49"
  ]
}

###

# Delete the comment by id
DELETE http://localhost:3333/api/comments/9 HTTP/1.1

###
