# Get comments for post by id
GET http://localhost:3333/api/comments/?postID=6 HTTP/1.1

###


# Create new comment for post by id
POST http://localhost:3333/api/comments/?postID=6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTU5MTA1LCJleHAiOjE2NzM5NjUxMDV9.ztRp5GiAyPJR5mpmw5ahZ_cEggQr3ywRmUqSExOmdvs
Content-Type: application/json

{
  "text": "new comment text",
  "userID": "639e73981ca903a10ea63fa3"
}

###

# Delete the comment by id
DELETE http://localhost:3333/api/comments/delete/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzhhNWJiZjRjYTc3NmJkMzI0NjA1ZGYiLCJlbWFpbCI6ImFkZHJlc3NAZG9tYWluLmJlYnJhIiwiaWF0IjoxNjczOTU5MTA1LCJleHAiOjE2NzM5NjUxMDV9.ztRp5GiAyPJR5mpmw5ahZ_cEggQr3ywRmUqSExOmdvs


###
